### ISSUE TITLE
no documentation built or published with new tag

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1128]
Once the definitions repository was tagged with [2022-06rc0](https://github.com/nexusformat/definitions/releases/tag/v2022.06rc0), no new documentation was built or published.  

@woutdenolf 
How is this supposed to work?

**Comment by woutdenolf** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push

`Runs your workflow when you push a commit or tag.`

We have

```yaml
name: Publish Sphinx Docs to GitHub Pages

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
```

So if you push a `tag` to the `main` branch, then this section should run

```yaml
    - name: Publish if refs/tags
      # remove/comment next line to push right away
      if: startsWith(github.ref, 'refs/tags')
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
```

**Comment by woutdenolf** [comment]
I guess you pushed the tag to another branch instead of the main branch?

**Comment by prjemian** [comment]
Appears to be the case.  I will tag again and confirm if docs are built & published.

**Comment by woutdenolf** [comment]
The yaml file might need this

```yaml
name: Publish Sphinx Docs to GitHub Pages

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
    tags:
      - '*'
```
