### ISSUE TITLE
BUG: no links to download vocabulary files

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1130]
The new vocabulary files are missing the download links: https://nexusformat.github.io/definitions/classes/index.html#downloads

**Comment by prjemian** [comment]
Also 404 (not found) error: https://nexusformat.github.io/definitions/_static/nxdl_vocabulary.html

**Comment by prjemian** [comment]
build html online:

```html
<tr class="row-even"><td><p><code class="xref download docutils literal notranslate"><span class="pre">/_static/nxdl_vocabulary.html</span></code></p></td>
<td><p>Human-readable HTML list of anchors, by vocabulary term, with links to the manual.</p></td>
</tr>
```

compare with local build

**Comment by prjemian** [comment]
local build:

```html
<tr class="row-even"><td><p><a class="reference download internal" download="" href="[../_downloads/dbcc5b21803e28207dd72ecba8d34e8a/nxdl_vocabulary.html](view-source:file://///zap/tmp/html/_downloads/dbcc5b21803e28207dd72ecba8d34e8a/nxdl_vocabulary.html)"><code class="xref download docutils literal notranslate"><span class="pre">/_static/nxdl_vocabulary.html</span></code></a></p></td>
<td><p>Human-readable HTML list of anchors, by vocabulary term, with links to the manual.</p></td>
</tr>
```

Wow!  Same source.  Need to refactor this.

**Comment by woutdenolf** [comment]
The nxdl_vocabulary are not deployed:

https://github.com/nexusformat/definitions/tree/gh-pages/_static/nxdl_vocabulary.html

**Comment by woutdenolf** [comment]
I'm looking at the workflow file

```
    - name: Prepare for out-of-source Sphinx build
      run: |
        rm -rf ./build
        mkdir ./build
        python ./utils/build_preparation.py . ./build

    - name: Build (html) and Commit
      uses: sphinx-notes/pages@master
      with:
        # path to conf.py directory
        documentation_path: build/manual/source
```

And I don't see how `nxdl2rst` is supposed to be executed.
