### ISSUE TITLE
new vocabulary should have NXDL version metadata

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1132]
The new vocabulary files (built from nxdl2rst.py) should have the NXDL version in them as metadata: https://github.com/nexusformat/definitions/blob/ca8a3d56f05e59d8d31098da6a0f5b91842c9321/NXDL_VERSION#L1

Here's the view of the JSON version right now:

```json
    "_metadata": {
        "datetime": "2022-06-24T17:25:29.987667",
        "title": "NeXus NXDL vocabulary.",
        "subtitle": "Anchors for all NeXus fields, groups, attributes, and links."
    },
```

**Comment by prjemian** [comment]
Will look like this:

```yaml
_metadata:
  datetime: '2022-06-25T21:52:45.135828'
  subtitle: Anchors for all NeXus fields, groups, attributes, and links.
  title: NeXus NXDL vocabulary.
  version: v2022.06
```
