### ISSUE TITLE
Wrong URL assigned by utils/nxdl2rst.py for contributed_definitions

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1149]
[Need] to fix the wrong category source URL issue with your suggestion in https://github.com/nexusformat/definitions/pull/1133#issuecomment-1170371459 before the merge then this PR will not change `build/html` output directory significantly. It means refactor [offered by #1133 will] not fix anything.

_Originally posted by @PeterC-DLS in https://github.com/nexusformat/definitions/issues/1133#issuecomment-1171354612_

**Comment by prjemian** [comment]
Here, `nxdl_file`` is an absolute path: https://github.com/nexusformat/definitions/blob/d9574a8f90626a929c677f1505729d1751170989/utils/nxdl2rst.py#L657

**Comment by PeterC-DLS** [comment]
I'm testing a change that adds a category argument to the `print_rst_from_nxdl` function.

**Comment by prjemian** [comment]
I'm working ona change that does not modify the call signature:

```py
def print_rst_from_nxdl(nxdl_file):
    """
    print restructured text from the named .nxdl.xml file
    """
    global listing_category

    nxdl_parent_dir = os.path.basename(os.path.dirname(nxdl_file))
```

**Comment by prjemian** [comment]
then these changes:

```py
    anchor_registry.category = nxdl_parent_dir  # SUBDIR_MAP[subdir]
```

and

```py
    # print(f"  {HTML_ROOT}/{SUBDIR_MAP[subdir]}/{name}.nxdl.xml")
    print(f"  {HTML_ROOT}/{nxdl_parent_dir}/{name}.nxdl.xml")
```

**Comment by prjemian** [comment]
> Here, `nxdl_file` is an absolute path:
> 
> https://github.com/nexusformat/definitions/blob/d9574a8f90626a929c677f1505729d1751170989/utils/nxdl2rst.py#L657

This is not correct.  The resulting YAML is missing the `nxdl_parent_dir` directory name:

```yaml
    /NXcxi_ptycho/DATA@axes-attribute:
      html: '#nxcxi-ptycho-data-axes-attribute'
      term: /NXcxi_ptycho/DATA@axes-attribute
      url: https://manual.nexusformat.org/classes//NXcxi_ptycho.html#nxcxi-ptycho-data-axes-attribute
```

Passing this information from the calling function (`main()`) is the most direct way to inform `print_rst_from_nxdl()`.

@PeterC-DLS : Is your branch ready?  I can discard mine.  It has not been pushed.
