### ISSUE TITLE
HTML artifacts for reviewers

### ISSUE THREAD

**Issue by woutdenolf** [nexusformat/definitions#1280]
When reviewing PRs you often want to see the rendered documentation. Currently you need to pull the branch and build locally. It would be much more convenient if you could see the documentation build by the CI.

**Comment by woutdenolf** [comment]
Possible solutions:

1. github workflow artifacts: https://github.com/nexusformat/definitions/pull/1041 (you still need to download the docs and view them locally)
2. readthedocs.org: you will be able to download the docs but they may be indexed by search engines

**Comment by woutdenolf** [comment]
When uploading to github-pages we should be able to see the docs for every merge request with `https://nexusformat.github.io/definitions/<your-branch>/`. But we don't. Do you think we enable this so we can see the rendered docs for easier reviewing?

```yaml
      - name: Deploy both the User Manual and the Impatient Guide
        if: ${{ github.event.inputs.deploy && env.python_version == env.python_deploy_version }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: build/html
```
