### ISSUE TITLE
add built documentation ZIP file artifact upload to CI workflow

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#1320]
As [demonstrated elsewhere](https://github.com/bluesky/hklpy/issues/281), upload a ZIP-file copy of the just-built documentation with each run of the CI workflow by adding these two steps.

This step should be added early in the workflow:

```yaml
    - name: Set env vars
      run: |
        export REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}  # just the repo, as opposed to org/repo
        echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_ENV
```

This step should be added just before the *deploy* step in the workflow:

```yaml
    - name: Upload Docs ZIP file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.REPOSITORY_NAME }}-docs
        path: docs/build/html/
```
