### ISSUE TITLE
nxdl2rst.py: document all the new anchors in one page

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#879]
Build a documentation page (separate? not part of the manual?), organized by keyword and context, listing all the anchors defined by #878.

For example, given the reST anchor `/NXdata/VARIABLE@last_good-attribute` (corresponds with HTML anchor `#nxdata-variable-last-good-attribute`), the keyword would be `@last_good` (converted to lower case) and the context would be `/NXdata/VARIABLE@last_good-attribute` with a link to the manual page anchor.  Any keyword with multiple contexts would be listed together, such as

* data
    * `/NXdata/DATA-field`
    * `/NXdetector/data-field`
    * `/NXentry/DATA-group`
  ..

Consider registering this list (2,517 items now) with an external registry, such as https://www.pidconsortium.net/.  [More details](http://dtr-test.pidconsortium.eu/#urls/intro.html)

**Comment by prjemian** [comment]
This code: https://github.com/nexusformat/definitions/blob/a841cc2152266da7446aab900acd68d2f6d938e6/utils/nxdl2rst.py#L29-L31 is the place to gather the reST anchor points from a single NXDL file.  The `nxdl2rst.py` program is run once for each NXDL file when building the documentation.

**Comment by prjemian** [comment]
As discussed in today's [telco](https://www.nexusformat.org/Telco_20210505.html), we could create a new repository in this GitHub organization to host the script-generated ontology files.  This would happen on every push to the main branch.  Tags in this repo would be created on the ontology repo as well.  Tags in the ontology repo could push the versioned ontology to a public service so that is findable.

The published ontology _describes_ the NeXus standard, it _does not define_ the standard.

**Comment by prjemian** [comment]
With #922, `.owl` file(s) will be created but still that does not describe how this content will be visualized.  So this issue cannot be closed yet.

**Comment by prjemian** [comment]
Looks like another type of index section.

**Comment by prjemian** [comment]
Will add a page that provides this content via a _download_ access so the full table (>2500 entries as of now) does not appear in the manual directly.  Will provide content in various formats including: json, yaml, and possibly xml.

Content will organize by keys (as described above).  Underneath, will provide all anchors using that key in at least two forms: full text anchor and URL to the documentation page

The files should also include some metadata about the date/time of creation and the git commit hash.  Basically something to inform about which version of the definitions is described by this content.

**Comment by prjemian** [comment]
Also, the `all_anchors.txt` file is a complete list of all hypertext anchors: https://github.com/nexusformat/definitions/blob/ed6f9fef29a1df54ec779ed0da2a81078320a890/utils/nxdl2rst.py#L32

**Comment by prjemian** [comment]
Possibly related to:
- #1057
- #1059

**Comment by prjemian** [comment]
Now, my PR is collecting information about each NXDL anchors just before it writes the anchors for that page.  Will we need to move this step, collecting the page anchors, before the page content is written?

**Comment by prjemian** [comment]
Here is a snippet:

### json

```json
        "pixel_mask": {
            "/NXdetector/pixel_mask-field": {
                "anchor": "/NXdetector/pixel_mask-field",
                "html": "#nxdetector-pixel-mask-field",
                "url": "https://manual.nexusformat.org/classes/base_classes/NXdetector.html#nxdetector-pixel-mask-field"
            },
            "/NXmx/ENTRY/INSTRUMENT/DETECTOR/pixel_mask-field": {
                "anchor": "/NXmx/ENTRY/INSTRUMENT/DETECTOR/pixel_mask-field",
                "html": "#nxmx-entry-instrument-detector-pixel-mask-field",
                "url": "https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx-entry-instrument-detector-pixel-mask-field"
            }
        },
        "pixel_mask_applied": {
            "/NXdetector/pixel_mask_applied-field": {
                "anchor": "/NXdetector/pixel_mask_applied-field",
                "html": "#nxdetector-pixel-mask-applied-field",
                "url": "https://manual.nexusformat.org/classes/base_classes/NXdetector.html#nxdetector-pixel-mask-applied-field"
            },
            "/NXmx/ENTRY/INSTRUMENT/DETECTOR/pixel_mask_applied-field": {
                "anchor": "/NXmx/ENTRY/INSTRUMENT/DETECTOR/pixel_mask_applied-field",
                "html": "#nxmx-entry-instrument-detector-pixel-mask-applied-field",
                "url": "https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx-entry-instrument-detector-pixel-mask-applied-field"
            }
        },
        "point_group": {
            "/NXsample/point_group-field": {
                "anchor": "/NXsample/point_group-field",
                "html": "#nxsample-point-group-field",
                "url": "https://manual.nexusformat.org/classes/base_classes/NXsample.html#nxsample-point-group-field"
            },
            "/NXsample_component/point_group-field": {
                "anchor": "/NXsample_component/point_group-field",
                "html": "#nxsample-component-point-group-field",
                "url": "https://manual.nexusformat.org/classes/base_classes/NXsample_component.html#nxsample-component-point-group-field"
            }
        },
```

### yaml

```yml
  pixel_mask:
    /NXdetector/pixel_mask-field:
      anchor: /NXdetector/pixel_mask-field
      html: '#nxdetector-pixel-mask-field'
      url: https://manual.nexusformat.org/classes/base_classes/NXdetector.html#nxdetector-pixel-mask-field
    /NXmx/ENTRY/INSTRUMENT/DETECTOR/pixel_mask-field:
      anchor: /NXmx/ENTRY/INSTRUMENT/DETECTOR/pixel_mask-field
      html: '#nxmx-entry-instrument-detector-pixel-mask-field'
      url: https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx-entry-instrument-detector-pixel-mask-field
  pixel_mask_applied:
    /NXdetector/pixel_mask_applied-field:
      anchor: /NXdetector/pixel_mask_applied-field
      html: '#nxdetector-pixel-mask-applied-field'
      url: https://manual.nexusformat.org/classes/base_classes/NXdetector.html#nxdetector-pixel-mask-applied-field
    /NXmx/ENTRY/INSTRUMENT/DETECTOR/pixel_mask_applied-field:
      anchor: /NXmx/ENTRY/INSTRUMENT/DETECTOR/pixel_mask_applied-field
      html: '#nxmx-entry-instrument-detector-pixel-mask-applied-field'
      url: https://manual.nexusformat.org/classes/applications/NXmx.html#nxmx-entry-instrument-detector-pixel-mask-applied-field
  point_group:
    /NXsample/point_group-field:
      anchor: /NXsample/point_group-field
      html: '#nxsample-point-group-field'
      url: https://manual.nexusformat.org/classes/base_classes/NXsample.html#nxsample-point-group-field
    /NXsample_component/point_group-field:
      anchor: /NXsample_component/point_group-field
      html: '#nxsample-component-point-group-field'
      url: https://manual.nexusformat.org/classes/base_classes/NXsample_component.html#nxsample-component-point-group-field
```
